config/routes.rb
KmapsSample::Application.routes.draw do
  resources :elements do
    resources :category_associations, :controller => 'category_element_associations'
    resources :associations, :controller => 'category_element_associations', :path => 'topics/:topic_id'
  end
  root :to => 'elements#index'
  

end

app/models/element.rb
class Element < ActiveRecord::Base
  validates_presence_of :title
  
  #belongs_to :category
  #belongs_to :second_category, :class_name => 'Category'
  has_many :category_element_associations, :dependent => :destroy
  
  CategoryElementAssociation::FIXED.each_pair{|root_id, associations| has_many associations, :dependent => :destroy, :class_name => 'CategoryElementAssociation', :conditions => {:root_id => root_id} }  
  has_many :not_fixed_associations, :dependent => :destroy, :class_name => 'CategoryElementAssociation', :conditions => ["root_id NOT IN (#{Array.new(CategoryElementAssociation::FIXED.size, '?').join(',')})"] + CategoryElementAssociation::FIXED.keys

  
  def category
    Category.find(self.category_id)
  end
  
  def second_category
    Category.find(self.second_category_id)
  end
  
  def roots
    self.category_element_associations.all(:select => 'DISTINCT root_id', :order => 'root_id').collect(&:root)
  end
end

# == Schema Info
# Schema version: 20110923200413
#
# Table name: elements
#
#  id                 :integer(4)      not null, primary key
#  category_id        :integer(4)
#  second_category_id :integer(4)
#  title              :string(255)
#  created_at         :datetime
#  updated_at         :datetime

app/controllers/elements_controller.rb
class ElementsController < AclController
  # GET /elements
  # GET /elements.xml
  def index
    @elements = Element.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @elements }
    end
  end

  # GET /elements/1
  # GET /elements/1.xml
  def show
    @element = Element.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @element }
    end
  end

  # GET /elements/new
  # GET /elements/new.xml
  def new
    @element = Element.new
    @root_category = Category.find(272)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = Element.find(params[:id])
    @root_category = Category.find(272)
  end

  # POST /elements
  # POST /elements.xml
  def create
    element_params = params[:element]
    association_params = {}
    element_params.keys.select{|key| key.include? 'associations'}.each{|key| association_params[key] = element_params.delete(key)}
    @element = Element.new(element_params)
    respond_to do |format|
      if @element.save
        associations = @element.category_element_associations
        association_params.each_value do |associations_param|
          category_ids = !associations_param.nil? && !associations_param[:category_ids].blank? ? associations_param[:category_ids].collect(&:to_i) : []
          root_id = !associations_param.nil? && !associations_param[:root_id].blank? ? associations_param[:root_id] : nil
          category_ids.each{|c_id| associations.create :category_id => c_id, :root_id => root_id.blank? ? Category.find(c_id).root.id : root_id}
        end
        flash[:notice] = 'Element was successfully created.'
        format.html { redirect_to elements_url }
        format.xml  { render :xml => @element, :status => :created, :location => @element }
      else
        @root_category = Category.find(272)
        format.html { render :action => "new" }
        format.xml  { render :xml => @element.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /elements/1
  # PUT /elements/1.xml
  def update
    @element = Element.find(params[:id])
    respond_to do |format|
      element_params = params[:element]
      association_params = {}
      element_params.keys.select{|key| key.include? 'associations'}.each{|key| association_params[key] = element_params.delete(key)}
      if @element.update_attributes(element_params)
        association_params.each_pair do |association_key, associations_param|
          associations = @element.send(association_key)
          associated_category_ids = associations.collect(&:category_id)
          category_ids_to_be_associated = !associations_param.nil? && !associations_param[:category_ids].blank? ? associations_param[:category_ids].collect(&:to_i) : []
          root_id = !associations_param.nil? && !associations_param[:root_id].blank? ? associations_param[:root_id] : nil
          (associated_category_ids - category_ids_to_be_associated).each{|c_id| associations.all(:conditions => {:category_id => c_id}).each(&:destroy)}
          (category_ids_to_be_associated - associated_category_ids).each{|c_id| associations.create :category_id => c_id, :root_id => root_id.blank? ? Category.find(c_id).root.id : root_id}
        end
        flash[:notice] = 'Element was successfully updated.'
        format.html { redirect_to elements_url }
        format.xml  { head :ok }
      else
        @root_category = Category.find(272)
        format.html { render :action => "edit" }
        format.xml  { render :xml => @element.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.xml
  def destroy
    @element = Element.find(params[:id])
    @element.destroy

    respond_to do |format|
      format.html { redirect_to(elements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
  def javascript_files
    uses_kmaps_integration ? super + ['jquery-ui', 'jquery.autocomplete', 'jquery.checktree', 'model-searcher', 'jquery.draggable.popup', 'ui-handler'] : super + ['ui-handler']
  end
  
  def stylesheet_files
    ['index'].include?(params[:action]) ? super + ['jquery-ui'] : super
  end
  
    
  private
  
  def uses_kmaps_integration
    ['index', 'new', 'edit'].include? params[:action]
  end
end

app/views/elements/_form.html.erb
<%= f.error_messages %>
<p><%= f.label :title %><br /><%= f.text_field :title %></p>
<%=	category_fields :subject => {:label => 'Single specific association (subject)'}, :root => @root_category, :var_name => :element, :field_name => :category, :include_js => false, :include_styles => true, :selectable => selectable, :single_selection => true %>
<%=	category_fields :subject => {:label => 'Single generic association'}, :var_name => :element, :field_name => :second_category, :include_js => false, :include_styles => false, :selectable => selectable, :single_selection => true %>
<%=	category_fields :subject => {:label => 'Multiple associations'}, :var_name => :element, :field_name => [:not_fixed_associations, :category], :include_js => false, :include_styles => false, :selectable => selectable, :single_selection => false %>
<%  CategoryElementAssociation::FIXED.each_pair do |root_id, associations| %>
<%=	  category_fields :subject => {:label => associations.humanize.titleize, :display => hidden_field_tag("element[#{associations}][root_id]", root_id)}, :root => Category.find(root_id), :var_name => :element, :field_name => [associations, :category], :show_dropdown => false, :include_js => false, :include_styles => false, :selectable => selectable, :single_selection => false %>
<%  end %>

app/views/elements/_form_fields.html.erb
<%= error_messages_for :element %>

<%=
	category_fields({
		:subject => {:display => 'Category', :label => 'Category Label'}, # 6/21/11 jev3a asks why is this hidden field in the label?
		:root => nil, #@root_category,  #nil
		:varname => :element,
		:hastree => 'true',
		:selectable => false,
		:fieldname => :category
	})
%>

<%=
	category_fields({
		:subject => {:display => 'Second Category', :label => 'Second Category Label'}, # 6/21/11 jev3a asks why is this hidden field in the label?
		:root => @root_category,  #nil
		:varname => :element,
		:hastree => 'true',
		:selectable => false,
		:fieldname => :second_category
	})
%>

app/views/elements/_persistent_links.html.erb
<%  if authorized? hash_for_element_path(:action => 'destroy') %>
<%=   link_to ts('delete.this'), @element, :confirm => te('delete.confirmation'), :method => :delete %> |
<%  end %>
<%= link_to 'Back to elements', elements_path %></p>

app/views/elements/edit.html.erb
<h1>Editing element</h1>
<%= form_for(@element) do |f| %>
<%=   category_form_table :locals => { :f => f, :selectable => true}, :form_partial => 'form', :footer => globalized_submit_tag('update.this', :style => 'margin-top:8px;') %>
<%  end %>
<p><%= render :partial => 'persistent_links' %></p>

app/views/elements/index.html.erb
<div id="popup_dialog"></div>
<h1>Listing elements</h1>
<table border="1">
  <tr>
    <th>Title</th>
    <th>Single Specific Association (Subject)</th>
    <th>Single Generic Association</th>
    <th>Multiple Associations</th>
  </tr>

<% @elements.each do |element| %>
  <tr>
    <td><%=link_to(h(element.title), authorized?(hash_for_edit_element_path) ? edit_element_path(element) : element_path(element)) %></td>
    <td><%=h(element.category.title) if element.category %></td>
    <td><%=h(element.second_category.title) if element.second_category %></td>
    <td>
<%=   render :partial => 'category_element_associations/index', :locals => {:category_associations => element.category_element_associations, :element => element} %>
    </td>
  </tr>
<% end %>
</table>
<p><%= link_to 'New element', new_element_path %></p>

app/views/elements/new.html.erb
<h1>New element</h1>
<%= form_for(@element) do |f| %>
<%=   category_form_table :locals => { :f => f, :selectable => true}, :form_partial => 'form', :footer => globalized_submit_tag('create.this', :style => 'margin-top:8px;') %>
<%  end %>
<%= link_to 'Back to elements', elements_path %></p>

app/views/elements/show.html.erb
<%= display_if_not_blank 'Title', h(@element.title) %>
<%= display_if_not_blank('Single Specific Association (Subject)', h(@element.category.title)) if !@element.category.nil? %>
<%= display_if_not_blank('Single Generic Association', h(@element.second_category.title)) if !@element.second_category.nil? %>
<%  associations = @element.category_element_associations
    if !associations.empty? %>
      <p><b>Multiple associations:</b>
<%    authorized_only hash_for_new_element_category_association_path do %>
(<%=    link_to 'new association', new_element_category_association_path(@element) %>)
<%    end %>
<%=   render :partial => 'category_element_associations/index', :locals => {:category_associations => associations, :element => @element} %></p>
<%  end %>
<p><% if authorized? hash_for_edit_element_path %>
<%=  link_to ts('edit.this'), edit_element_path(@element) %> |
<% end %>
<%= render :partial => 'persistent_links' %>
</p>