config/routes.rb
KmapsSample::Application.routes.draw do
  resources :elements do
    resources :category_associations, :controller => 'category_element_associations'
    resources :associations, :controller => 'category_element_associations', :path => 'topics/:topic_id'
  end
  root :to => 'elements#index'
  

end

app/models/category_element_association.rb
class CategoryElementAssociation < ActiveRecord::Base
  validates_presence_of :category_id
  belongs_to :element
  
  FIXED = {286 => 'grammatical_function_associations', 272 => 'subject_associations'}
  
  def category_stack
    stack = []
    stack << self.label if !label.blank? && self.prefix_label
    stack << self.root.title if self.show_root?
    stack << self.category.parent.title if self.show_parent?
    stack << self.category.title
    stack.last << " #{self.label}" if !label.blank? && !self.prefix_label
    stack
  end
  
  def stacked_category
    return category_stack.join(' > ')
  end
  
  def category
    Category.find(self.category_id)
  end
  
  def root
    Category.find(self.root_id)
  end
  
  
end

# == Schema Info
# Schema version: 20110923200413
#
# Table name: category_element_associations
#
#  id           :integer(4)      not null, primary key
#  category_id  :integer(4)      not null
#  element_id   :integer(4)      not null
#  root_id      :integer(4)      not null
#  label        :string(255)
#  prefix_label :boolean(1)      not null, default(TRUE)
#  show_parent  :boolean(1)      not null
#  show_root    :boolean(1)      not null, default(TRUE)
#  created_at   :datetime
#  updated_at   :datetime

app/controllers/category_element_associations_controller.rb
class CategoryElementAssociationsController < AclController
  before_filter :find_element_and_topic
  
  # GET /category_element_associations
  # GET /category_element_associations.xml
  def index
    if @topic.nil?
      @category_element_associations = @element.category_element_associations
    else
      @category_element_associations = @element.category_element_associations.all(:conditions => {:root_id => @topic.id})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @category_element_associations }
    end
  end

  # GET /category_element_associations/1
  # GET /category_element_associations/1.xml
  def show
    @category_element_association = CategoryElementAssociation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category_element_association }
    end
  end

  # GET /category_element_associations/new
  # GET /category_element_associations/new.xml
  def new
    @category_element_association = @element.category_element_associations.new
    respond_to do |format|
      format.html # new.html.erb
      format.js   { render 'new' }
      format.xml  { render :xml => @category_element_association }
    end
  end

  # GET /category_element_associations/1/edit
  def edit
    @category_element_association = CategoryElementAssociation.find(params[:id])
  end

  # POST /category_element_associations
  # POST /category_element_associations.xml
  def create
    association_param = params[:category_element_association]
    category_ids = association_param[:category_id]
    if category_ids.nil?
      redirect_to(elements_url)
    elsif category_ids.size==1
      association_param[:category_id] = category_ids.first
      association_param[:root_id] = Category.find(association_param[:category_id]).root.id
      @category_element_association = @element.category_element_associations.new(association_param)
      respond_to do |format|
        if @category_element_association.save
          format.html { redirect_to(elements_url, :notice => 'CategoryElementAssociation was successfully created.') }
          format.xml  { render :xml => @category_element_association, :status => :created, :location => @category_element_association }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @category_element_association.errors, :status => :unprocessable_entity }
        end
      end
    else
      category_ids.each{ |c_id| @element.category_element_associations.create :category_id => c_id, :root_id => Category.find(c_id).root.id } if category_ids.size>1
      redirect_to(elements_url, :notice => 'CategoryElementAssociation was successfully created.')
    end
  end

  # PUT /category_element_associations/1
  # PUT /category_element_associations/1.xml
  def update
    @category_element_association = CategoryElementAssociation.find(params[:id])

    respond_to do |format|
      if @category_element_association.update_attributes(params[:category_element_association])
        format.html { redirect_to(elements_url, :notice => 'CategoryElementAssociation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category_element_association.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /category_element_associations/1
  # DELETE /category_element_associations/1.xml
  def destroy
    @category_element_association = CategoryElementAssociation.find(params[:id])
    @category_element_association.destroy

    respond_to do |format|
      format.html { redirect_to(elements_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def find_element_and_topic
    @element = params[:element_id].blank? ? nil : Element.find(params[:element_id])
    @topic = params[:topic_id].blank? ? nil : Category.find(params[:topic_id])
  end
end

app/helpers/category_element_associations_helper.rb
module CategoryElementAssociationsHelper
end

app/views/category_element_associations/_form.html.erb
<%= f.error_messages %>
<%=	category_fields :subject => {:label => 'Category'}, :var_name => :category_element_association, :field_name => :category, :field_human_name => 'Kmap topic', :include_js => false, :include_styles => true, :selectable => selectable, :single_selection => single_selection,
		:extra_fields => [{:field => f.check_box(:show_parent), :label => "Show category\'s immediate parent"},
        {:field => f.check_box(:show_root), :label => 'Show top level Knowledge Map'},
        {:field => "#{f.text_field(:label)} #{f.radio_button(:prefix_label, true)} Prefix with > &nbsp;&nbsp;&nbsp;&nbsp;#{f.radio_button(:prefix_label, false)} 'SPACE suffix'", :label => CategoryElementAssociation.human_attribute_name(:label)}] %>

app/views/category_element_associations/_index.html.erb
<% if !category_associations.empty? %>
     <ul>
<%   category_associations.each do |association| %>
       <li>
<%       stack = association.category_stack
         stack.push(link_to(h(stack.pop), authorized?(hash_for_edit_element_category_association_path) ? edit_element_category_association_path(element, association) : element_category_association_path(element, association))) %>
<%=      stack.join(' > ').html_safe %>
       </li>
<%   end %>
     </ul>
<% end
   if authorized? hash_for_new_element_category_association_path
	 links = [link_to('Add more', new_element_category_association_path(element)), link_to('Add more with UI', new_element_category_association_path(element), :remote => true, :class => 'ui_dialog')] %>
<%   links += element.roots.collect{|c| link_to "#{c.title}", element_associations_path(element, c) } %>
     <p><%= links.join(' | ').html_safe %></p>
<% end %>

app/views/category_element_associations/_new.html.erb
<h1>New category_element_association</h1>
<%= form_for(:category_element_association, :url => element_category_associations_path(@element)) do |f| %>
<%=   category_form_table :locals => { :f => f, :selectable => true, :single_selection => false}, :form_partial => 'form', :footer => globalized_submit_tag('creat.e.this', :style => 'margin-top:8px;') %>
<%  end %>

app/views/category_element_associations/_persistent_links.html.erb
<%  if authorized? hash_for_element_category_association_path(:action => 'destroy') %>
<%=   link_to ts('delete.this'), element_category_association_path(@element, @category_element_association), :confirm => te('delete.confirmation'), :method => :delete %> |
<%  end %>
<%= link_to ts('back.to', :what => @element.title), authorized?(hash_for_edit_element_path) ? edit_element_path(@element) : element_path(@element) %> |
<%= link_to 'Back to elements', elements_path %>

app/views/category_element_associations/edit.html.erb
<h1>Editing category_element_association</h1>
<%= form_for(:category_element_association, :url => element_category_association_path(@element, @category_element_association), :html => { :method => :put }) do |f| %>
<%=   category_form_table :locals => { :f => f, :selectable => true, :single_selection => true}, :form_partial => 'form', :footer => globalized_submit_tag('update.this', :style => 'margin-top:8px;') %>
<%  end %>
<p><%= render :partial => 'persistent_links' %></p>

app/views/category_element_associations/index.html.erb
<h1>Listing associations to <%= @element.title %></h1>
<%= render :partial => 'index', :locals => {:category_associations => @category_element_associations, :element => @element} %>
<%= link_to 'New category_element_association', new_element_category_association_path(@element) %> |
<%= link_to ts('back.to', :what => @element.title), authorized?(hash_for_edit_element_path) ? edit_element_path(@element) : element_path(@element) %> |
<%= link_to 'Back to elements', elements_path %>

app/views/category_element_associations/new.html.erb
<%= render :partial => 'new' %>
<%= link_to 'Back to associations', element_category_associations_path(@element) %> |
<%= link_to ts('back.to', :what => @element.title), authorized?(hash_for_edit_element_path) ? edit_element_path(@element) : element_path(@element) %> |
<%= link_to 'Back to elements', elements_path %>

app/views/category_element_associations/new.js.erb
$("#popup_dialog").html("<%= escape_javascript(render(:partial => 'new')) %>")

app/views/category_element_associations/show.html.erb
<p>
  <b>Element:</b>
  <%=h @category_element_association.element.title %>
</p>
<p><%= @category_element_association.stacked_category %></p>
<p>&nbsp;<br/>
<% if authorized? hash_for_edit_element_category_association_path %>
<%=  link_to ts('edit.this'), edit_element_category_association_path(@element, @category_element_association) %> |
<% end %>
<%= render :partial => 'persistent_links' %></p>